delete from ldfbs_suffix_filter;
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(1,'Microsoft Office Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(2,'Microsoft Outlook Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(3,'iWorks Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(4,'OpenOffice');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(5,'Abiword');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(6,'Other Commom Office Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(7,'Multimedia Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(8,'Images');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(9,'System Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(10,'Web content');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(11,'Compressed Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(12,'Fax Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(13,'Disk Images');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(14,'Virtual Images');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(15,'Temporary Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(16,'Java Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(17,'Delphi Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(18,'C++ Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(19,'C# Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(20,'Android Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(21,'IOS Files');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(22,'All');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(23,'1.办公软件');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(24,'2.图形图像');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(25,'3.工程设计');
INSERT INTO `ldfbs_suffix_filter`(`SF_ID`,`SF_NAME`) VALUES(26,'4.开发语言');

delete from ldfbs_suffix_filter_suffix;
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.doc',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dot',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pwi',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.psw',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pwd',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wps',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xls',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xlt',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xlw',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wk4',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wk3',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wk1',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wks',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wq1',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dbf',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dif',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.slk',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xla',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mdb',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mda',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mde',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ade',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.adp',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vsd',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vdx',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vss',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vsx',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vst',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vtx',1);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mpp',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mpt',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mpd',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ppt',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pps',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pot',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ppa',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xsn',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pub',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.docm',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.docx',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dotm',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dotx',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.potm',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.potx',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ppam',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ppsm',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ppsx',1);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pptm',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pptx',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xlam',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xlsb',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xlsm',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xlsx',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xltm',1);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xltx',1);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pst',2);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pab',2);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.nk2',2);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.olm',2);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mbox',2);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pages',3);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.numbers',3);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.keynote',3);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.key',3);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.apxl',3);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.key-tef',3);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.nmbtemplate',3);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pages-tef',3);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.doc',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dot',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xml',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.docx',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.docm',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dotx',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dotm',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wpd',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wps',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.rtf',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.txt',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.csv',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sdw',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sgl',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vor',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.uot',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.uof',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.jtd',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.jtt',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.hwp',4);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.602',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pdb',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.psw',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xls',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xlw',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xlt',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xlsx',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xltx',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xltm',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xlsb',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wk1',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wks',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.123',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dif',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dbf',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.slk',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.uos',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pxl',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wb2',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ppt',4);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pps',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pot',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pptx',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pptm',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.potx',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.potm',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sda',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sdd',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sdp',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.uop',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cgm',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.odt',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ott',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sxw',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.stw',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sxc',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.stc',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sdc',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sxi',4);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sti',4);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.abw',5);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.zabw',5);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.abw.gz',5);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pdf',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tiff',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tif',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.abw',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.csv',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.emf',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.emz',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.lwp',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mcw',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.odf',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.odm',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.odp',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ods',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.odt',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ott',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.rtf',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.svg',6);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.svgz',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wpd',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wri',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wps',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mmp',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.bmf',6);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.aac',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.aif',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.aiff',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.apl',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.asf',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.asx',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.au',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.avi',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cda',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dvr-ms',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ifo',7);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.kar',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.m1v',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.m2v',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.m3u',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.m4a',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.m4b',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mid',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.midi',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.miz',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mov',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mp1',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mp2',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mp3',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mp4',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mpa',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mpe',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mpeg',7);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mpg',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mv',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.nsa',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.nsv',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ogg',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pls',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ram',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.rmi',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.snd',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vlb',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vob',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.voc',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wma',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wav',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wmv',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wax',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wm',7);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wmd',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wmx',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wpl',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wvx',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.a52',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ac3',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ape',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.b4s',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.divx',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dv',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.flac',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.flv',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.m2t',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.m2ts',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.m3u8',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.m4v',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mkv',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mpeg1',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mpeg2',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mpeg4',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mts',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mxf',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.nuv',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ogm',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ogv',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.oqx',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ps',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.qgf',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.rec',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.rm',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.rmvb',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.swf',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tod',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ts',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vlc',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wv',7);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.3gp',7);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wbmp',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wbm',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tif',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tiff',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.bmp',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dib',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.rle',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ai',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.art',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.eps',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.png',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.fh',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ft',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.gif',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.jpe',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.jpeg',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.psd',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cdr',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cmx',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cpt',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pdd',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pdn',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.psp',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wmf',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.yuv',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.odg',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dwg',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dxf',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.emf',8);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.emz',8);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.com',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.exe',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.msi',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dll',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ocx',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.inf',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.msc',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.bat',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ini',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.log',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.properties',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tmp',9);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dat',9);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mht',10);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mhtml',10);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.htm',10);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.html',10);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.js',10);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.rar',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tar.gz',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.zip',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.gz',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cab',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.bz2',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.arj',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.7z',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.jar',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ace',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.7zip2',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cpio',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.deb',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.gzip',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.hfs',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.lha',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.lzh',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.lzma',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.rpm',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.split',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.swm',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tar',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.taz',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tbz',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tbz2',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tgz',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tpz',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wim',11);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xar',11);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tiff',12);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tif',12);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dmg',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.gho',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ghs',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.iso',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mdf',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.mds',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.nrg',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.nvram',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.avhd',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.bin',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.gi',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.isz',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cue',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ashdisc',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.b6t',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.b6i',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.bwt',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.bwi',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.lcd',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dvd',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ccd',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.img',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.daa',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cdi',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cif',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xmf',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xmd',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pdi',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.timg',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.hfs',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ncd',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pxi',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.p2i',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.rif',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.rdf',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.uif',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vc4',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vcd',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ima',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.bif',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.flp',13);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.c2d',13);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vdi',14);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vmdk',14);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vmsd',14);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vmx',14);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vmxf',14);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.nvram',14);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vhd',14);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.bin',14);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.hdd',14);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sav',14);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pvs',14);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.temp',15);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.tmp',15);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.java',16);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.js',16);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.jsp',16);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.css',16);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xml',16);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.html',16);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.php',16);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.net',16);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.BPL',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.CAB',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.CFG',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DCP',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DCU',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DFM',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.～DF',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dll',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DOF',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DPK',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DPL',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DPR',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.～DP',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DSK',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DSM',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.OCX',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.PAS',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.～PA',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.RES',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.STR',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.TLB',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DCI',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DRO',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DMT',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DBI',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DEM',17);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.DCT',17);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.h',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.hpp',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.hxx',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cpp',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cc',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cxx',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.C',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.c++',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dll',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.lib',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ini',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.log',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sln',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ncb',18);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.db',18);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.sln',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.csproj',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.aspx',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ascx',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.aspx.cs',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.cs',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.asax',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.config',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.aspx.resx',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.resx',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.XSD',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pdb',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.suo',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.asmx',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.vsdisco',19);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.htc',19);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.apk',20);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.deb',21);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.*',22);

INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.doc',23);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xls',23);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.ppt',23);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pdf',23);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.dps',23);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.wps',23);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.eio',23);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.txt',23);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.docx',23);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.xlsx',23);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.pptx',23);
INSERT INTO `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) VALUES('.et',23);

insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.psd', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.fh11', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.fh12', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.fh9', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.fh8', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.gif', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.png', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.tif', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.tag', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.cdr', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.ai', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.jpg', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.jpe', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.jpeg', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.bmp', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.tiff', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.wmf', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.jfif', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.pic', 24);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.dib', 24);

insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.dwg',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.dxf',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.prt.*',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.prt',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.asm',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.dft',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.pcf',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.sldprt',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.sldasm',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.slddrw',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.exb',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.ics',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.icd',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.dgn',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.elt',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.mc9',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.max',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.ddb',25);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.pcb',25);

insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.sln', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.csproj', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.aspx', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.ascx', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.sapx', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.cs', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.asax', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.config', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.aspx', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.resx', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.XSD', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.pdb', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.suo', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.asmx', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.vsdisco', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.htc', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.h', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.hpp', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.hxx', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.cpp', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.cc', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.cxx', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.c', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.c++', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.dll', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.lib', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.ini', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.log', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.sln', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.ncb', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.db', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.java', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.js', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.jsp', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.css', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.xml', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.html', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.php', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.net', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.asm', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.for', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.lib', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.lst', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.msg', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.obj', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.psa', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.wki', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.bas', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.deb', 26);
insert into `ldfbs_suffix_filter_suffix`(`SF_SUFFIX`,`SF_ID`) values('.apk', 26);

